# Generated by Django 4.2.2 on 2023-06-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_mymodelname_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModelName',
        ),
    ]
