# Generated by Django 4.2.2 on 2023-06-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_remove_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
    ]
